# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a47c99894c13c0ef81bca7754d30f5851c55e836a8e46d862a2ba08941c55b1cf834aac6e354bf6cd0aee9158dac11d38e4eb0c087fa5c9aa583857fa07a2966
  auth0_client_id: uOI0y1sg9RtpvCVjPvvUMYWVNJqETjfk
  auth0_client_secret: peDNSEZTOcthqNEqL0_If7cP1O5IkHLNuzTVlGt9nAtLDf8zADQ2E8cjfOffwHRe

test:
  secret_key_base: 116576c375ca711a60b2e90670759f0b69f42e3cc2487c554423b5cb68d8b9b7f27c8d0907b2ca6105ee6adf587985b9fc94893cbac9ba3a9e1289ecbe23af0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
